services:
  go:
    build:
      context: ./context/go
      dockerfile: Dockerfile
    container_name: go
    environment:
      - GO_ENV=${GO_ENV}
      - DB_HOST=${MONGO_HOST}
      - DB_PORT=${MONGO_HOST_PORT}
      - DB_USER=${MONGO_INITDB_ROOT_USERNAME}
      - DB_PASS=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ${GO_SRC}:/app
      - ${GO_CONFIG}:/config
      - ${GO_DATA}:/data
      - ${GO_LOGS}:/logs
    depends_on:
      - mongodb
    ports:
      - "${GO_APP_HOST_PORT}:8080"

  java:
    build:
      context: ./context/java
      dockerfile: Dockerfile
    container_name: java
    environment:
      - JAVA_ENV=${JAVA_ENV}
    volumes:
      - ${JAVA_SRC}/target:/app
      - ${JAVA_CONFIG}:/config
      - ${JAVA_DATA}:/data
      - ${JAVA_LOGS}:/logs
    ports:
      - "${JAVA_APP_HOST_PORT}:8081"

  python:
    build:
      context: ./context/python
      dockerfile: Dockerfile
    container_name: python
    environment:
      - PY_ENV=${PY_ENV}
    volumes:
      - ${PYTHON_SRC}:/app
      - ${PYTHON_CONFIG}:/config
      - ${PYTHON_DATA}:/data
      - ${PYTHON_LOGS}:/logs
    ports:
      - "${PY_APP_HOST_PORT}:8082"

  mongodb:
    build:
      context: ./context/mongodb
      dockerfile: Dockerfile
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ${MONGODB_DATA}:/data/db
      - ${MONGODB_LOGS}:/logs
      - ${MONGODB_CONFIG}/mongod.conf:/etc/mongod.conf
    ports:
      - "${MONGO_HOST_PORT}:27017"

  uptimekuma:
    build:
      context: ./context/uptimekuma
      dockerfile: Dockerfile
    container_name: uptimekuma
    volumes:
      - ${UPTIME_KUMA_DATA}:/data
      - ${UPTIME_KUMA_LOGS}:/logs
      - ${UPTIME_KUMA_CONFIG}:/config
    ports:
      - "${UPTIME_KUMA_HOST_PORT}:3001"
